[package]
name = "coio"
version = "0.1.0"
authors = ["Gleb Pomykalov <gleb@pomykalov.ru>"]

[dependencies]

[dependencies.coio]
git = "https://github.com/zonyitoo/coio-rs.git"

[dependencies.time]
version = "0.1"
